language: node_js
node_js:
  - "10"
  - "11"
  
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
  yarn: true
  
#before_script:
#  - npm 
  
script: npm test # Here you could also run the build step of your application


# before_deploy: npm install now --no-save # Install Now CLI on Travis
# before_install:
#  - 
deploy:
  - provider: script
#    script: npm run travis:staging
#    script: yarn run test
    script: npm run test
    skip_cleanup: true
    on:
      master: true
  - edge: true
    provider: script
#    script: npm run travis:production
#    script: yarn run test
    script: npm run test
    skip_cleanup: true
    on:
      tags: true
